# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            btkm
tagline:          Блог о путешествиях и вообще
url:              http://butkam.github.io/btkm_blog/
paginate:         1
baseurl:          /btkm_blog/
author:
  name:           Антон Поляков
  url:            https://www.facebook.com/anton.polyakov
  email:          anton.poliakov@btkm.net

# Custom vars
version:          1.0.0
github:
  repo:           
