# Permalinks
permalink:        btkm
relative_permalinks: false

# Setup
title:            btkm
tagline:          Блог о путешествиях и вообще
url:              http://btkm.net
paginate:         1
baseurl:          /
author:
  name:           Антон Поляков
  url:            https://www.facebook.com/anton.polyakov
  email:          anton.poliakov@btkm.net

# Custom vars
version:          1.0.0
github:
  repo:           
